### ISSUE TITLE
Error - Failed to save "config.json"

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#15]
This is a continuation of https://github.com/nylas/nylas-mail/issues/3382

Users are seeing issues with either not being able to save the config.json file or the config.json file becomes corrupt for some reason.

![image](https://cloud.githubusercontent.com/assets/549323/26831992/0637e9ae-4a9c-11e7-980d-97494e142193.png)

**Comment by seesemichaelj** [comment]
@dweremeichik I'm still having issues with executing fresh Nylas install on Windows with PR https://github.com/nylas/nylas-mail/pull/3567 given your suggestions. I downloaded the 2013 VC redistributable still with no avail.

Typically there are 6 nylas processes running but I only see 3:
![image](https://cloud.githubusercontent.com/assets/549323/26832232/d25ee4f6-4a9c-11e7-9a88-ca4ab4f22ba7.png)

Have you been able to do a successful Windows update/install?

**Comment by dweremeichik** [comment]
@seesemichaelj I have not tried to get Windows to build locally until today. I am starting from a fresh VM and installing dependencies as things fail. I am looking to get this documented so that others can build without issue as well.

**Comment by seesemichaelj** [comment]
I've been doing some dumb/lazy debugging; when I get more time tonight I'll take a more in depth look and hope to figure it out. Let me know if you make progress; I will as well

**Comment by seesemichaelj** [comment]
Alright, I was able to get this to build for Windows and get the install to work properly. I have provided a non-signed (I don't know how this may affect installation as I don't know how Windows handles non-code signed applications; I've never needed to sign my small applications before!) install. This Install will essentially uninstall previous versions of Nylas and install this one (sorry I couldn't figure out how to do the update). Please follow the below steps to get it to work. I am NOT liable for any loss of data (nor should it happen) or any bad things that may happen to you by installing my version of the application.

1. I am only providing a Windows build; if you need a Mac or Linux package, let us know and we can figure out how to get you that.
2. Close Nylas
3. The process should keep your old configuration and email database, but to be safe let's make a copy of it. It should be stored at `C:\Users\{yourusernamehere}\.nylas_mail\`. Make a copy of the folder to you location of choice.
4. Download the new installation file at https://drive.google.com/open?id=0B3p_Z9HIEFr_bjF5bERzLXpyNE0
5. Run the install file! It may fail almost immediately, probably because Nylas is still running in the background. Try again. If it still has issues, you may need to open task manager and end all nylas.exe processes
6. After install, it should open your Nylas as you had it configured before! Your email should be there and accounts setup. Check the version by opening the menu in top right and see that it says "Version 2.0.15". Also verify by going to `C:\Users\{yourusernamehere}\.nylas_mail\` and see files like `config.149...json`.
7. Nylas will download and try to update itself. You MUST resist not to press the update button or you'll need to do this process over again as the update will overwrite my changes.
8. Run with this version and see if the issue occurs. Tell me here if it does; tell me here if it doesn't and you would have definitely expected to happen by then.

Cheers!

**Comment by Zangoran** [comment]
I have updated to your build, so far no problems. But is there any way that we can merge this pull into the 2.0.32 build?

**Comment by dweremeichik** [comment]
@Zangoran as of right now, no. Unless Nylas decides to merge it. Our fork is behind theirs by quite a bit due to the state of their github. @seesemichaelj did find archived code that is as recent as 2.0.31. Not sure if we want to pull that in or if we just want to wait for them (Nylas) to push back to github.

**Comment by seesemichaelj** [comment]
@Zangoran I'll see if it's feasible to do a 2.0.31 build tomorrow or Friday. We would need a source code drop from Nylas to get 2.0.32 which I wouldn't count on for the near-term.

I'll comment on this whether or not I can provide an updated build. Thanks for helping test!

**Comment by seesemichaelj** [comment]
False alarm. It appears the source code I found in the Releases tab is any different than what is in Github; we do not have any source code after 2.0.15 and would need a source code drop from Nylas.

**Comment by seesemichaelj** [comment]
As per @andrelefevre mentioned on the other issue, I am having issues sending emails from my accounts. I'm looking into the issue. Is anyone not seeing this issue?

**Comment by andrelefevre** [comment]
Installing the version was no problem! But syncing of the accounts (I have 5 accounts) and sending email for all 5 is giving errors! They are not sent!

**Comment by seesemichaelj** [comment]
You're having issues syncing as well or just sending?

**Comment by andrelefevre** [comment]
Hi Mike,

Both!!!!

Andre 
--
André le Fèvre
Telephone: +31-20-8943702 [tel:+31-20-8943702]
Mobile: +31-6-51958530 [tel:+31-6-51958530]
Email: alefevre@ziggo.nl [mailto:alefevre@ziggo.nl]
Skype: alefevre55
--
[http://img240.imagevenue.com/img.php?image=th_656124318_ALFphotoemail_122_164lo.jpg]
--
Sent from my Laptop
Op 8-6-2017 15:44:21, Mike Seese <notifications@github.com> schreef:
You're having issues syncing as well or just sending?

**Comment by seesemichaelj** [comment]
@andrelefevre Ok. I'm only seeing issues with sending (the issue I'm receiving is "Reason: Cannot read propery 'substring' of undefined"; is this the same for you? I can receive mail just fine across multiple accounts. If you're getting frustrated that it's not working, please go ahead and either take the update or download the official install at https://www.nylas.com/nylas-mail/ :)

Thanks for helping! I'm looking into the issue in the meantime.

**Comment by andrelefevre** [comment]
Hi,  

I will have a more detailled answer for you tomorrow! I have some meetings ahead now!  

Warm regards,  
André


--


André le Fèvre


Sales Director EMEA and India

Ardor Learning Inc.

Global Corporate Market Distributor for  

--

Walenburg 23, 1965 MD, Heemskerk(x-apple-data-detectors://2/0)


The Netherlands(x-apple-data-detectors://2/0)


--


Telephone: +31-20-8943702(tel:+31-20-8943702)


Mobile: +31-6-51958530(tel:+31-6-51958530)


Email: andre.lefevre@ardorlearning.com(mailto:andre.lefevre@ardorlearning.com)


Web: www.myoxfordenglish.com(http://www.myoxfordenglish.com/)


Web: www.ardorlearning.com(http://www.ardorlearning.com/)


--


Learning is not attained by chance, it must be sought for with ardor and diligence (Abigail Adams)


--


Sent from my iPhone/iPad with AirMail




Van: Mike Seese <notifications@github.com>(mailto:notifications@github.com)
Beantwoorden: nylas-mail-lives/nylas-mail <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 8 juni 2017 at 16:01:06
Aan: nylas-mail-lives/nylas-mail <nylas-mail@noreply.github.com>(mailto:nylas-mail@noreply.github.com)
Cc: andrelefevre <alefevre@ziggo.nl>(mailto:alefevre@ziggo.nl), Mention <mention@noreply.github.com>(mailto:mention@noreply.github.com)
Onderwerp: Re: [nylas-mail-lives/nylas-mail] Error - Failed to save "config.json" (#15)

**Comment by dweremeichik** [comment]
@seesemichaelj I'm pretty sure there is an issue related to that bug filed in the main nylas repo. May be related.

**Comment by dweremeichik** [comment]
Found it... https://github.com/nylas/nylas-mail/issues/3583

**Comment by paulmartimx** [comment]
@seesemichaelj Testing your build wide in my office, 4+ installations with 2 email accounts each one. I'll let you know.

**Comment by seesemichaelj** [comment]
Thanks @paulmartimx! Just so you know, my build still has the sent email issue (where you cannot send emails). I believe you should be able to receive emails. I haven't had time to look into/fix the sent email issue yet.

**Comment by paulmartimx** [comment]
@seesemichaelj Receiving OK. Testing sending.

**Comment by paulmartimx** [comment]
@seesemichaelj Tested. Sending didn't work.  BUT config.json problems are gone.


Here full output:

Cannot read property 'substring' of undefinedTypeError: Cannot read property 'substring' of undefined
    at pathForBodyFile (message-body-utils.es6:32:21)
    at Object.writeBody (message-body-utils.es6:41:20)
    at setBody (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\internal_packages\client-sync\src\models\message.js:39:52)
    at Instance.set (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\sequelize\lib\instance.js:312:32)
    at obj.(anonymous function) [as set] (/internal_packages\client-sync\src\shared\shim-sequelize.es6:19:27)
    at Instance.set (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\sequelize\lib\instance.js:294:16)
    at obj.(anonymous function) [as set] (/internal_packages\client-sync\src\shared\shim-sequelize.es6:19:27)
    at initValues (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\sequelize\lib\instance.js:63:8)
    at Instance (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\sequelize\lib\instance.js:107:14)
    at new Instance (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\sequelize\lib\model.js:686:14)
    at Model.build (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\sequelize\lib\model.js:1764:10)
    at Object.<anonymous> (message-utils.es6:430:28)
    at next (<anonymous>)
    at step (message-utils.es6:2:1)
    at Model.<anonymous> (message-utils.es6:2:1)
    at Model.tryCatcher (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)Error
    at new APIError (/src\flux\errors.es6:57:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src\flux\syncback-task-api-request.es6:30:25)
    at EventEmitter.eventHandler (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\reflux\src\PublisherMethods.js:36:22)
    at EventEmitter.emit (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\eventemitter3\index.js:72:35)
    at Function.trigger (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\reflux\src\PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\reflux\src\createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/src\services\delta-processor.es6:139:13)
    at /src\services\delta-processor.es6:77:12
    at next (<anonymous>)
    at step (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\src\services\delta-processor.js:35:191)
    at C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\src\services\delta-processor.js:35:361
    at tryCatcher (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromiseCtx (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:10)
    at Async._drainQueue (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\Personal\AppData\Local\NylasMail\app-2.0.15\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)

**Comment by seesemichaelj** [comment]
Perfect, thanks @paulmartimx. I'll post on this issue when I think I've fixed the sending issue!

**Comment by seesemichaelj** [comment]
A new set of binaries were snapped which include this fix as well as the sending email fix: https://github.com/nylas-mail-lives/nylas-mail/releases/tag/2.1.0
