### ISSUE TITLE
unable to build or run the client on mac

### ISSUE THREAD

**Issue by aramix** [nylas-mail-lives/nylas-mail#204]
after `npm install` and `npm run client` I get this screen:
![image](https://user-images.githubusercontent.com/1033320/38340312-d7e12300-3883-11e8-9827-58bcd9ec804a.png)
I get this screen even if I download and install it from the latest release

When I try to build it using `npm run build-client` I get the following error:
```
---> Packaging for 1s
---> Packaging for 2s
---> Packaging for 3s
---> Packaging for 4s
---> Packaging for 5s
---> Packaging for 6s
---> Packaging for 7s
Packaging app for platform darwin x64 using electron v1.8.4
---> Packaging for 8s
---> Packaging for 9s
---> Packaging for 10s
---> Packaging for 11s
---> Packaging for 13s
---> Packaging for 14s
---> Packaging for 16s
---> Packaging for 18s
---> Packaging for 19s
---> Packaging for 20s
---> Packaging for 21s
---> Packaging for 23s
---> Packaging for 24s
---> Packaging for 25s
---> Packaging for 26s
---> Packaging for 27s
Fatal error: ENOTEMPTY: directory not empty, rename '/var/folders/ds/yljt734n7z5dntdrnjr3q8qm0000gn/T/nylas-build/electron-packager/darwin-x64/Nylas Mail-darwin-x64/Electron.app/Contents/Resources/apm/node_modules/atom-package-manager/node_modules' -> '/var/folders/ds/yljt734n7z5dntdrnjr3q8qm0000gn/T/nylas-build/electron-packager/darwin-x64/Nylas Mail-darwin-x64/Electron.app/Contents/Resources/apm/node_modules'

npm ERR! Darwin 17.5.0
npm ERR! argv "/Users/aramix/.nvm/versions/node/v6.9.1/bin/node" "/Users/aramix/.nvm/versions/node/v6.9.1/bin/npm" "run" "build-client"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! nylas-mail-all@0.0.1 build-client: `grunt build-client --gruntfile=packages/client-app/build/Gruntfile.js --base=./`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the nylas-mail-all@0.0.1 build-client script 'grunt build-client --gruntfile=packages/client-app/build/Gruntfile.js --base=./'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nylas-mail-all package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build-client --gruntfile=packages/client-app/build/Gruntfile.js --base=./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nylas-mail-all
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nylas-mail-all
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aramix/nylas-mail/npm-debug.log
```
Specs:
macOS Hight Sierra 10.13.4
python 2.7.13
node 6.9.1
npm 3.10.8

Is this something already known? What would be the fix?

**Comment by aramix** [comment]
Ok, so the problem is that in the latest commit there are some blind version upgrades to fix vulnerability issues. That needs to be fixed as there are incompatibility issues after a version bump

**Comment by seesemichaelj** [comment]
Thanks for looking into. As this isn't maintained anymore, I did not test the version changes. If you could make a PR that fixes the issue you're having while also resolving the CVE vulnerability problems, that would be great.

**Comment by scurrvy2020** [comment]
same issue on linux, ubuntu 16.04 and 18.04. 

> Streaming log data to /tmp/Nylas-Mail-11930.log
Error: The module '/usr/share/nylas-mail/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Debug/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/usr/share/nylas-mail/resources/app.asar/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/better-sqlite3/lib/database.js:5:38)
    at Object.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/better-sqlite3/index.js:2:18)
    at Object.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/better-sqlite3/index.js:36:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/database-helpers.es6:2:1)
    at Object.<anonymous> (/src/database-helpers.es6:66:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/browser/database-reader.es6:1:1)
    at Object.<anonymous> (/usr/share/nylas-mail/resources/app.asar/src/browser/database-reader.js:38:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/browser/application.es6:15:1)
    at Object.<anonymous> (/usr/share/nylas-mail/resources/app.asar/src/browser/application.js:955:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at App.app.on (/usr/share/nylas-mail/resources/app.asar/src/browser/main.js:236:25)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7) {}

**Comment by hmhofman** [comment]
I have the same thing. 
Using Arch Linux
npm v6.1.0
node v10.4

**Comment by aramix** [comment]
It does not depend on what version of node or npm you use, it's internal package dependance issues, that needs to be fixed. I would love to do that but don't have enough time for now. Instead I went with a previois commit.

**Comment by seesemichaelj** [comment]
Just so you all know, there isn't anyone planning on fixing this. This repository is no longer maintained. If you want to become a maintainer, you can let me know.
