### ISSUE TITLE
Unable to install plugins because of APM error

### ISSUE THREAD

**Issue by sGerli** [nylas-mail-lives/nylas-mail#75]
When I try to install plugins I get the following error:
`Running apm install failed to install package dependencies.`

##### Are there any related issues?
No

##### What operating system are you using?
Windows 10

2.1.0

--

**Bug?** Yes
##### Do you have any third-party plugins installed? If so, which ones?
No (because of this bug)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

**Comment by seesemichaelj** [comment]
This needs more info please (sorry, the labels don't notify changes to the issue)

**Comment by sGerli** [comment]
@seesemichaelj this issue persists in 2.2.0 , what can I provide you with?

**Comment by redking974** [comment]
Hi, I've got the same issue with 2.2.0. What means exactly apm ? Atom Package Manager ?
Because I don't have Atom installed, is it mandatory to install plugins ?

Regards.

**Comment by seesemichaelj** [comment]
sorry @sGerli I guess I missed your question. I guess I was commenting on @dweremeichik's behalf since he applied the label without asking for more info haha

Have either of you tried to install other plugins? Which plugins have you tried?

@redking974 ya not sure how `apm` works with this. if it is required, it should be packaged with the install.

**Comment by sGerli** [comment]
Yeah, I've tried n1-unsubscribe, n1-github, and n1-avatars .

**Comment by seesemichaelj** [comment]
Alright; well FYI n1-unsubscribe should be built in. See #49

**Comment by redking974** [comment]
In fact, I've seen none of the plugins built-in and I can't install plugins manually.
![sans titre](https://user-images.githubusercontent.com/23528297/31744236-5d9c1b4e-b45e-11e7-82b2-9b6a3f57c3ae.jpg)
I try with debug flags enabled as recommanded by the app but no more success.

**Comment by dweremeichik** [comment]
Well that's strange. It appears that the built in plugins are perhaps still there, note the unsubscribe tab to the right in your image.

**Comment by chadidi** [comment]
I have the same problem on windows 10 it was working in Linux

**Comment by dweremeichik** [comment]
From what I gather, this appears to be Windows only.

**Comment by laedit** [comment]
Detailed error:
> "Fetching local packages failed."

StackTrace:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ([user]\AppData\Local\NylasMail\app-2.2.2\resources\apm\node_modules\git-utils\lib\git.js:8:16)
    at Object.<anonymous> ([user]\AppData\Local\NylasMail\app-2.2.2\resources\apm\node_modules\git-utils\lib\git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by laedit** [comment]
Related warning:

```
Unhandled rejection
Error: Fetching local packages failed.
    at /src\apm-wrapper.coffee:44:21
    at exit (/src\apm-wrapper.coffee:20:7)
    at triggerExitCallback (/src\buffered-process.coffee:210:9)
    at /src\buffered-process.coffee:222:9
    at Socket.<anonymous> (/src\buffered-process.coffee:123:7)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
From previous event:
    at APMWrapper.module.exports.APMWrapper.getInstalled (/src\apm-wrapper.coffee:90:5)
    at Store._onPackagesChanged (/internal_packages\plugins\lib\packages-store.jsx:189:15)
    at Store._prepareIfFresh (/internal_packages\plugins\lib\packages-store.jsx:128:10)
    at Store.installed (/internal_packages\plugins\lib\packages-store.jsx:99:10)
    at TabInstalled._getStateFromStores (/internal_packages\plugins\lib\tab-installed.jsx:32:31)
    at TabInstalled (/internal_packages\plugins\lib\tab-installed.jsx:16:23)
    at [user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:295:18
    at measureLifeCyclePerf ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._constructComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:280:21)
    at ReactCompositeComponentWrapper.mountComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:188:21)
    at Object.mountComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:516:12)
    at Object.mountComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:258:21)
    at Object.mountComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper._updateRenderedComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:765:40)
    at ReactCompositeComponentWrapper._performComponentUpdate ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:547:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at Object.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:208:32)
    at ReactDOMComponent._updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:936:12)
    at ReactDOMComponent.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:754:10)
    at ReactDOMComponent.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:716:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at Object.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:208:32)
    at ReactDOMComponent._updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:936:12)
    at ReactDOMComponent.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:754:10)
    at ReactDOMComponent.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:716:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at Object.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:208:32)
    at ReactDOMComponent._updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:936:12)
    at ReactDOMComponent.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:754:10)
    at ReactDOMComponent.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:716:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:547:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at Object.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:208:32)
    at ReactDOMComponent._updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:936:12)
    at ReactDOMComponent.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:754:10)
    at ReactDOMComponent.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:716:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:547:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at Object.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:208:32)
    at ReactDOMComponent._updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:936:12)
    at ReactDOMComponent.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:754:10)
    at ReactDOMComponent.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactDOMComponent.js:716:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:547:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:547:10)
    at Object.receiveComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:561:12)
    at Object.performUpdateIfNecessary ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:157:22)
    at runBatchedUpdates ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactUpdates.js:150:21)
    at ReactReconcileTransaction.perform ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\Transaction.js:140:20)
    at ReactUpdatesFlushTransaction.perform ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\Transaction.js:140:20)
    at Object.flushBatchedUpdates ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\Transaction.js:206:25)
    at ReactDefaultBatchingStrategyTransaction.perform ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\Transaction.js:153:16)
    at dispatchEvent ([user]\AppData\Local\NylasMail\app-2.2.2\resources\app.asar\node_modules\react-dom\lib\ReactEventListener.js:147:20)
```
