### ISSUE TITLE
Message successfully sent, trouble saving to your sent folder - can't find sent folder - could not save message to sent folder.

### ISSUE THREAD

**Issue by dweremeichik** [nylas-mail-lives/nylas-mail#95]
For some reason, my sent folder on one of my accounts is not appearing correctly, I ended up with the following error.
```
Error
    at new APIError (/src/flux/errors.es6:57:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:30:25)
    at EventEmitter.eventHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/nylas-mail/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/nylas-mail/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/usr/share/nylas-mail/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/src/services/delta-processor.es6:139:13)
    at /src/services/delta-processor.es6:77:12
    at next (<anonymous>)
    at step (/usr/share/nylas-mail/resources/app.asar/src/services/delta-processor.js:35:191)
    at /usr/share/nylas-mail/resources/app.asar/src/services/delta-processor.js:35:361
    at tryCatcher (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by dweremeichik** [comment]
It appears that the EnsureMessageInSentFolderTask has failed with APIError 500 Can't find sent folder - could not save message to sent folder.

**Comment by ckoulatsi** [comment]
i have the same issue. When i try to see more info the popup msg just vanish. Another issue i have is that nylas can't sync my mails.
